name: CRGravestones
main: org.golde.bukkit.corpsereborngravestones.Main
version: 1.0
author: Eric Golde
description: An unfinished plugin that adds gravestones to your world.
website: http://eric.golde.org/
depends: ["CorpseReborn", "WorldEdit"]