name: NoItemsNoCorpse
main: org.golde.bukkit.corpserebornaddons.noitemsnocorpse.Main
version: 1.1
author: Eric Golde
description: CorpseReborn addon. Cancles creation of corpse if player has no items.
website: http://eric.golde.org/
depend: [CorpseReborn]