name: LootCorpseInRadius
main: org.golde.bukkit.corpserebornaddons.lootcorpseinradius.Main
version: 1.1
author: Eric Golde
description: A custom made addon for CorpseReborn that puts a message in your actionbar telling you that a corpse is near by and you can click to loot it
website: http://eric.golde.org/
depend: [CorpseReborn]

permissions:
  craddons.lootinradius:
    default: op
    description: Permission to loot in radius